### ISSUE TITLE
Dates for Rt estimates

### ISSUE THREAD

**Issue by ibulu** [epiforecasts/covid-regional#3]
Hi,
Really great initiative. I am looking at rt.csv file in the https://github.com/epiforecasts/covid-regional/tree/master/united-states/regional-summary folder. I can not find the associated dates for these estimates in the rt.csv file. How can I find the dates associated with the Rt estimates?

**Comment by seabbs** [comment]
Hi @ibulu. 

Apologies it looks like the date was inadvertently dropped from the summary file on the last update. I have just corrected this so it will be back for future updates (starting tomorrow morning).
